services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pgdata/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${PGSQL_DATABASE}
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
    ports:
      - "5432:5432"
    restart: always

  web:
    build: ./octopus/.
    working_dir: /app
    volumes:
      - ./octopus:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
