services:
  db:
    container_name: db
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pgdata/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${PGSQL_DATABASE}
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
      - TZ=America/Toronto
    ports:
      - "5432:5432"
    restart: always

  web:
    container_name: web
    build: ./octopus/.
    working_dir: /app
    volumes:
      - ./octopus:/app
      - /app/node_modules
    ports:
      - "80:3000"
    depends_on:
      - db
    restart: always
    environment:
      - TZ=America/Toronto

volumes:
  pgdata:
